# Site settings
title: Iconize Everything
name: Iconize Everything
locale: en_us
logo: img/logo.png
header-img: img/home-cover.png
email: nupur91shah@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://bumpyrides.in/IconizeEverything"
author:
  facebook:     nupur.shah.1654
  twitter:      nupurshah91
  google_plus:  NupurShah91
  github: nupurshah91

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
